trigger:
- main

#CRON à modifier suivant récurrence voulue

schedules:
- cron: "0 18 1 1 *"
  displayName: repetition
  branches:
    include:
    - main
  always: true

pool:
  vmImage: ubuntu-latest