apiVersion: apps/v1
kind: Deployment
metadata:
  name: appvote
  labels:
    app: appvotetag
spec:
  selector:
    matchLabels:
      app: appvotetag
  replicas: 2
  template:
    metadata:
      labels:
        app: appvotetag
    spec:
      containers:
      - name: appvote
        image: simplonasa/azure_voting_app:{{ version }}
        resources:
          requests:
            cpu: 250m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "rediscluster"
        - name: REDIS_PWD
          valueFrom:
            secretKeyRef:
              name: redis
              key: REDIS_PWD
        - name: STRESS_SECS
          value: "2"
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: autoscalevoteapp
spec:
  maxReplicas: 8
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voteapp
  targetCPUUtilizationPercentage: 70
---
apiVersion: v1
kind: Service
metadata:
  name: lbappvote
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: appvotetag